# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 17:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_company_name', models.CharField(max_length=20)),
                ('customer_email', models.CharField(max_length=100)),
                ('order_number', models.CharField(max_length=6)),
                ('contact_country', models.CharField(max_length=2)),
                ('contact_question', models.TextField(max_length=200)),
                ('contact_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.CharField(max_length=10)),
                ('item_origin', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('shipping_address', models.TextField(max_length=200)),
                ('shipping_zipcode', models.CharField(max_length=6)),
                ('shipping_country', models.CharField(max_length=2)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('company_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_address', models.TextField(max_length=200)),
                ('company_zipcode', models.CharField(max_length=5)),
                ('company_country', models.CharField(max_length=2)),
            ],
        ),
    ]
