# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_contry', models.CharField(max_length=2)),
                ('contact_question', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Item_name', models.CharField(max_length=200)),
                ('item_price', models.CharField(max_length=10)),
                ('item_origin', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('shipping_address', models.TextField(max_length=200)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('company_address', models.TextField(max_length=200)),
                ('company_contact', models.CharField(max_length=10)),
                ('company_country', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Retailer'),
        ),
        migrations.AddField(
            model_name='contact',
            name='order_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Order'),
        ),
    ]
