# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20171127_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_contact',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_zipcode',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
