# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20171127_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_contact',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='company_contact',
        ),
        migrations.AddField(
            model_name='retailer',
            name='company_zipcode',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
