# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_order_shipping_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Item_name',
            new_name='item_name',
        ),
    ]
