# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20171128_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_contry',
            new_name='contact_country',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
