# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_auto_20171128_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_company',
        ),
        migrations.AddField(
            model_name='contact',
            name='company_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='order_number',
            field=models.CharField(max_length=6),
        ),
    ]
