# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_auto_20171128_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='company_name',
            new_name='contact_company_name',
        ),
    ]
