# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_auto_20171128_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_time',
        ),
    ]
