# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_remove_contact_contact_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
