# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_contact_contact_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='customer_email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
